version: "3"
services:

 web:
  image: leolegends/microservices_php:multitenancy
  volumes:
   - "./..:/app"
  environment:
   WEB_DOCUMENT_ROOT: /app/public
   PHP_MEMORY_LIMIT: 4096M
  ports:
   - "85:80"
  networks:
   - gestor_avalie_network

 mysql:
  image: mysql:8.0
  ports:
    - 3338:3306
  environment:
   MYSQL_ROOT_PASSWORD: 123
   MYSQL_DATABASE: avalie
   MYSQL_USER: avalie
   MYSQL_PASSWORD: 123
  networks: 
    - gestor_avalie_network
  volumes:
    - mysql_avalie_data:/var/lib/mysql

networks:
 gestor_avalie_network:

volumes:
  mysql_avalie_data:
